#+title: Makas
#+category: Makas
#+description: Cut your Textile into a nice website.
#+options: toc:nil

#+BEGIN_QUOTE
*BEWARE ALPHA SOFTWARE!*

I use this library for my own website w/o problems, but it has not
been tested with different setups yet, and is not complete.  Use at
your own risk.  That said, the source code is rather brief, so you can
review easily and decide for yourself.
#+END_QUOTE

* Synopsis
*Makas* generates websites from a tree of [[https://www.promptworks.com/textile][Textile]] files.  It does
not try to deduce any meaning from the structure of that tree
(i.e. where files are in the directory hierarchy), but can generate a
blog from a directory of files named a certain way, if enabled.  See
[[file:doc/example-config/scripts/single-blog.rb][this example]] for how that can be done.  Multiple blogs, RSS feed
generation and copying over static files are supported.

* Dependencies
The Makas library depends on the Ruby standard runtime and the
[[http://redcloth.org/][RedCloth]] library.  See [[file:Gemfile.lock]] for exact versions.

* Usage
Documentation is TBD as this was just extracted from my own personal
blog.  But in the meantime the [[file:doc/][example files]] can be used to make a
working website.

* Contributing
Please open an issue or mail me a patch.  Document your changes
accurately and completely, and write nicely formatted, readable,
elegant, and carefully produced code.

* License
Copyright (C) 2017-2018  Göktuğ Kayaalp <self@gkayaalp.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

* Issues
** TODO When copying static files, exception if target does not exist and >= 2 levels
Seemingly [[file:lib/makas.rb::target.delete%20if%20target.exist?][this]]

:        Dir.mkdir target_dir if !target_dir.exist?

has to be modified.

#+BEGIN_EXAMPLE
/home/g/co/makas/lib/makas.rb:301:in `mkdir': No such file or directory @ dir_s_mkdir - output/.well-known/acme-challenge (Errno::ENOENT)
	from /home/g/co/makas/lib/makas.rb:301:in `block in copy_static_files'
	from /home/g/co/makas/lib/makas.rb:299:in `each'
	from /home/g/co/makas/lib/makas.rb:299:in `map'
	from /home/g/co/makas/lib/makas.rb:299:in `copy_static_files'
	from /home/g/co/makas/lib/makas.rb:420:in `build_site'
	from /home/g/co/makas/lib/makas.rb:433:in `build_site'
	from ./scripts/build.rb:27:in `<main>'
#+END_EXAMPLE

** TODO Support Scss and Sass
Automatically convert, if enabled, S*ss files to CSS files during
build.

** TODO =blog/index.rss.xml= mode shoud be 644, but is 640
somehow the [[file:Makefile::umask%200022%20&&%20bundle%20exec%20ruby%20build.rb][umask]] does not apply to it.

** TODO Allow arbitrarily-deep breadcrumbs.
See [[file:lib/makas.rb::crumbs%20=%20@link.each_filename.to_a]]

** TODO Generate a sitemap
[[file:lib/makas.rb::def%20generate_pages%20sources_root,%20target_root,%20templates,%20force_regeneration][generate-pages]] should be able to initiate that, given it has a list of
pages already.
